version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn --version
      - mvn clean install
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo build complete react-and-spring-data-rest:0.0.2
artifacts:
  files:
    - target/spring-1.0.jar
