version: 0.2

phases:
  install:
    commands:
      - mv /usr/local/bin/docker /usr/bin/docker
      - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - echo Creating Docker Compose Context
      - curl "http://169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}" > creds.json
      - cat creds.json
      - export AWS_ACCESS_KEY_ID=$(cat creds.json | jq -r .AccessKeyId)
      - echo $AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$(cat creds.json | jq -r .SecretAccessKey)
      - echo $AWS_SECRET_ACCESS_KEY
      - export AWS_SESSION_TOKEN=$(cat creds.json | jq -r .Token)
      - echo $AWS_SESSION_TOKEN
      - docker context create ecs demoecs --from-env
      - docker context use demoecs
  build:
    commands:
      - echo Build started on `date`
      - echo Convert Compose File
      - docker compose up
      - echo docker image after build
      - docker images