version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo maven version check
      - mvn --version
      - mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - export IMAGE_TAG=latest
  post_build:
    commands:
      - echo Build completed on `date`
      - printf '[{"name":"hello-world","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
